<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="dash.scss">
</head>

<div class="container container--narrow-sidebar staticpage">

	<div class="staticpage_wrapper my-account">

		<div class="staticpage_content">



			<div class="page-title"><h1>My Dashboard</h1></div>

			<div class="dashboard">

			<p class="lead">Hi David, nice to see you!</p>

			<div class="dashboard_section dashboard_section--account">

			    <div class="heading-group">
			        <h2>Info and Password</h2>

			        <a class="button button--s button--subtle" href="#">
			            Edit        </a>
			    </div>

			    <table class="simple-table m-b-0">
			        <tbody><tr>
			            <th>Name</th>
			            <td>David Jaguttis</td>
			        </tr>

			        <tr>
			            <th>Email</th>
			            <td>david@jaguttis.ca</td>
			        </tr>

			        <tr>
			            <th>Password</th>
			            <td><a href="#">Change Password</a></td>
			        </tr>
			    </tbody></table>
			</div>


			<div class="dashboard_section dashboard_section--orders">
			    <div class="heading-group">
			        <h2>Recent Orders</h2>

			                    <a class="button button--s button--subtle"href="#">View All</a>
			            </div>




			                <table class="table recent-orders-table">
			                    <thead>
			                        <tr>
			                            <th>Date</th>



						<th>Status</th>
							<th>Total</th>
									          <th>Order #</th>
			                        </tr>
			                    </thead>

			                    <tbody>
			                         <tr>
	                                <td>Jun 15, 2017</td>
	 																<td>Pending</td>
	                                <td><span class="price">$63.25</span></td>
<td><a href="#">100000956 - View</a> <a class="button button--s button--wide" href="#">Track Package</a></td>
			                         </tr>
			                         <tr>
	                                <td>May 10, 2017</td>
	 																<td>Pending</td>
	                                <td><span class="price">$128.52</span></td>
<td><a href="#">10000452 - View</a> <a class="button button--s button--wide" href="#">Track Package</a></td>
			                         </tr>
			                         <tr>
	                                <td>Jan 22, 2016</td>
	 																<td>Pending</td>
	                                <td><span class="price">$14.32</span></td>
<td><a href="#">100000321 - View</a> <a class="button button--s button--wide" href="#">Track Package</a></td>
			                         </tr>
			                                            </tbody>
			                </table>

			    </div>

			    <div class="dashboard_section dashboard_section--newsletter">
			        <div class="heading-group">
			            <h2>Newsletter</h2>

			            <a class="button button--s button--subtle" href="#">
			                Manage            </a>
			        </div>

			        <p>Edit your newsletter subscriptions.</p>
			    </div>


			<div class="dashboard_section dashboard_section--address">
			    <div class="heading-group">
			        <h2>Addresses</h2>

			        <a class="button button--s button--subtle" href="#">
			            Manage        </a>
			    </div>

			    <ul class="card-list">
			        <li class="card-list_item">
			            <div class="card-list_card">
			                <h5>Default Billing Address</h5>
			                <p>David Jaguttis<br>

			10939 Old Manchaca Rd<br>
			Austin,  Texas, 78748<br>
			United States<br>
			T: 5127663196<br>
			<a class="button button--s button--subtle m-b-0 ed" href="#">Edit</a>
			</p>
			            </div>
			        </li>

			        <li class="card-list_item">
			            <div class="card-list_card">
			                <h5>Default Shipping Address</h5>
			                <p>David Jaguttis<br>

			10939 Old Manchaca Rd<br>
			Austin,  Texas, 78748<br>
			United States<br>
			T: 5127663196<br>
			<a class="button button--s button--subtle m-b-0 ed" href="#">Edit</a>
			</p>

			            </div>
			        </li>
			    </ul>
			</div>

			</div>
		</div><!-- .staticpage_content -->

		<div class="staticpage_sidebar">

			<h2>My Account</h2>
			<ul>
				<li class="current"><a href="account.php">Account Dashboard</a></li>
				<li><a href="#">Info and Password</a></li>
				<li><a href="#">Address Book</a></li>
				<li><a href="order.php">My Orders</a></li>
				<li><a href="#">My Wishlist</a></li>
				<li><a href="#">Newsletter Subscription</a></li>
				<li><a href="#">Store Credit</a></li>
			</ul>
		</div><!-- .staticpage_sidebar -->

	</div><!-- .staticpage_wrapper -->

</div>
